name: photogtaphy
favicon: null
layout_spectrum: 0.14117931621149182
typography_spectrum: 0.4844175602775067
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fafafa'
    - '#010302'
    - '#2a312a'
    - '#d3cac1'
    - '#789b64'
  brandStrength: 0.8703192370012403
  lightness: 0.9226540282834321
  saturation: 0.6765924147330225
  rhythmicContrast: 0.17091762297786772
purpose: []
